[package]
name = "rp2040-async"
version = "0.1.0"
edition = "2021"

[dependencies]
rp2040-hal = "0.10.0"
critical-section = "1.2.0"
embedded-hal-async = "1.0.0"
#defmt = "0.3.8"

[features]
alarm0 = []
alarm1 = []
alarm2 = []
alarm3 = []
dma0 = []
dma1 = []
